apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000 # Expose the service on port 80
      targetPort: 8000 # Map it to FastAPI's port
  type: ClusterIP
