DISTRICTS = {
    "D01": "Boat Quay / Raffles Place / Marina",
    "D02": "Chinatown / Tanjong Pagar",
    "D03": "Alexandra / Commonwealth",
    "D04": "Harbourfront / Telok Blangah",
    "D05": "Buona Vista / West Coast / Clementi",
    "D06": "City Hall / Clarke Quay",
    "D07": "Beach Road / Bugis / Rochor",
    "D08": "Farrer Park / Serangoon Rd",
    "D09": "Orchard / River Valley",
    "D10": "Tanglin / Holland",
    "D11": "Newton / Novena",
    "D12": "Balestier / Toa Payoh",
    "D13": "Macpherson / Potong Pasir",
    "D14": "Eunos / Geylang / Paya Lebar",
    "D15": "East Coast / Marine Parade",
    "D16": "Bedok / Upper East Coast",
    "D17": "Changi Airport / Changi Village",
    "D18": "Pasir Ris / Tampines",
    "D19": "Hougang / Punggol / Sengkang",
    "D20": "Ang Mo Kio / Bishan / Thomson",
    "D21": "Clementi Park / Upper Bukit Timah",
    "D22": "Boon Lay / Jurong / Tuas",
    "D23": "Bukit Batok / Bukit Panjang / Choa Chu Kang",
    "D24": "Lim Chu Kang / Tengah",
    "D25": "Admiralty / Woodlands",
    "D26": "Mandai / Upper Thomson",
    "D27": "Sembawang / Yishun",
    "D28": "Seletar / Yio Chu Kang",
}

PLAN_AREA_MAPPING = {
    "ANG MO KIO": "D20",
    "BEDOK": "D16",
    "BISHAN": "D20",
    "BOON LAY": "D22",
    "BUKIT BATOK": "D23",
    "BUKIT MERAH": "D03",
    "BUKIT PANJANG": "D23",
    "BUKIT TIMAH": "D21",
    "CENTRAL WATER CATCHMENT": "D24",
    "CHANGI": "D17",
    "CHANGI BAY": "D17",
    "CHOA CHU KANG": "D23",
    "CLEMENTI": "D05",
    "DOWNTOWN CORE": "D01",
    "GEYLANG": "D14",
    "HOUGANG": "D19",
    "JURONG EAST": "D22",
    "JURONG WEST": "D22",
    "KALLANG": "D14",
    "LIM CHU KANG": "D24",
    "MANDAI": "D26",
    "MARINA EAST": "D01",
    "MARINA SOUTH": "D01",
    "MARINE PARADE": "D15",
    "MUSEUM": "D01",
    "NEWTON": "D11",
    "NORTH-EASTERN ISLANDS": "D24",
    "NOVENA": "D11",
    "ORCHARD": "D09",
    "OUTRAM": "D02",
    "PASIR RIS": "D18",
    "PAYA LEBAR": "D14",
    "PIONEER": "D22",
    "PUNGGOL": "D19",
    "QUEENSTOWN": "D03",
    "RIVER VALLEY": "D09",
    "ROCHOR": "D07",
    "SELETAR": "D28",
    "SEMBAWANG": "D27",
    "SENGKANG": "D19",
    "SERANGOON": "D08",
    "SIMPANG": "D24",
    "SINGAPORE RIVER": "D01",
    "SOUTHERN ISLANDS": "D01",
    "STRAITS VIEW": "D01",
    "SUNGEI KADUT": "D25",
    "TAMPINES": "D18",
    "TANGLIN": "D10",
    "TENGAH": "D24",
    "TOA PAYOH": "D12",
    "TUAS": "D22",
    "WESTERN ISLANDS": "D24",
    "WESTERN WATER CATCHMENT": "D24",
    "WOODLANDS": "D25",
    "YISHUN": "D27",
}
