name: Build and Push Propnex Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - airflow
    paths:
      - "pkg/scrapers/scraper.py"
      - "pkg/scrapers/propnex-scraper.py"
      - "pkg/scrapers/entrypoint.sh"
      - "pkg/scrapers/Dockerfile.Propnex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: pkg/scrapers/Dockerfile.Propnex
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:propnex-scraper-latest
