name: Build and Push 99co Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - airflow
    paths:
      - "pkg/scrapers/scraper.py"
      - "pkg/scrapers/99co-scraper.py"
      - "pkg/scrapers/entrypoint.sh"
      - "pkg/scrapers/Dockerfile.99co"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: pkg/scrapers/Dockerfile.99co
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:99co-scraper-latest
