name: Lint and Format

on:
  push:
    branches:
      - main
      - airflow
  pull_request:
    branches:
      - main

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to commit changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-docstrings autopep8

      # Auto-fix Python code
      # -v -> verbose
      # -i -> modifies in-place
      # -r -> recursively
      # -a -> aggressive (try to fix everything)
      - name: Run autopep8
        run: |
          autopep8 -vv -i -r -aa pkg airflow

      # Run flake8 to check the code for linting issues
      - name: Run flake8
        run: |
          flake8 -v pkg airflow

      - name: Commit changes
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'pull_request')
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-fix and format code with black and autopep8"
          git push
